
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 10 00:30:21 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 40;
  public static final int CHAR = 48;
  public static final int CONST = 3;
  public static final int CASE = 17;
  public static final int LPAREN = 38;
  public static final int GREATER = 28;
  public static final int CONTINUE = 11;
  public static final int LESS = 30;
  public static final int FOR = 12;
  public static final int MINUS = 19;
  public static final int RPAREN = 39;
  public static final int SEMICOLON = 34;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int BOOL = 46;
  public static final int COMMA = 36;
  public static final int INC = 24;
  public static final int DIV = 21;
  public static final int QUESTION_MARK = 44;
  public static final int LESS_EQUAL = 31;
  public static final int PLUS = 18;
  public static final int ASSIGN = 23;
  public static final int IF = 14;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 41;
  public static final int GREATER_EQUAL = 29;
  public static final int NEW = 5;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 20;
  public static final int NUMBER = 47;
  public static final int MOD = 22;
  public static final int NEQ = 27;
  public static final int IDENT = 45;
  public static final int BREAK = 10;
  public static final int VOID = 9;
  public static final int EQ = 26;
  public static final int SWITCH = 16;
  public static final int COLON = 35;
  public static final int LBRACE = 42;
  public static final int ELSE = 15;
  public static final int ENUM = 4;
  public static final int READ = 7;
  public static final int RBRACE = 43;
  public static final int DEC = 25;
  public static final int PRINT = 6;
  public static final int LENGTH = 13;
}

