
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 23 09:13:17 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAM = 2;
  public static final int LBRACE = 3;
  public static final int IDENT = 11;
  public static final int BOOL = 12;
  public static final int NUMBER = 13;
  public static final int EOF = 0;
  public static final int EQ = 6;
  public static final int RBRACKET = 9;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int SEMICOLON = 10;
  public static final int LBRACKET = 8;
  public static final int RBRACE = 4;
  public static final int CHAR = 14;
  public static final int CONST = 5;
}

